# Form implementation generated from reading ui file 'pharmacistRegister.ui'
#
# Created by: PyQt6 UI code generator 6.10.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout.addItem(spacerItem, 6, 4, 1, 1)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.IDEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.IDEdit.setObjectName("IDEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.SpanningRole, self.IDEdit)
        self.emailEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.emailEdit.setObjectName("emailEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.SpanningRole, self.emailEdit)
        self.firstNameEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.firstNameEdit.setObjectName("firstNameEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.SpanningRole, self.firstNameEdit)
        self.lastNameEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lastNameEdit.setObjectName("lastNameEdit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.SpanningRole, self.lastNameEdit)
        self.passwordEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.passwordEdit.setObjectName("passwordEdit")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.SpanningRole, self.passwordEdit)
        self.pharmacisRegistertSubmit = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pharmacisRegistertSubmit.setObjectName("pharmacisRegistertSubmit")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.ItemRole.SpanningRole, self.pharmacisRegistertSubmit)
        self.gridLayout.addLayout(self.formLayout, 6, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 25))
        self.menubar.setObjectName("menubar")
        self.menuregistration = QtWidgets.QMenu(parent=self.menubar)
        self.menuregistration.setObjectName("menuregistration")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuregistration.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.IDEdit.setText(_translate("MainWindow", "pharmacistID"))
        self.emailEdit.setText(_translate("MainWindow", "Email"))
        self.firstNameEdit.setText(_translate("MainWindow", "First Name"))
        self.lastNameEdit.setText(_translate("MainWindow", "Last Name"))
        self.passwordEdit.setText(_translate("MainWindow", "Password"))
        self.pharmacisRegistertSubmit.setText(_translate("MainWindow", "Register as Pharmacist"))
        self.menuregistration.setTitle(_translate("MainWindow", "Registration"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
